name: Deploy app to server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: deploy

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Deploy to host
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: -rltgoDzvO --delete
          SOURCE: ./dist
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
